# Generated by Django 4.2.3 on 2023-07-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='totle',
            new_name='title',
        ),
    ]
