# Generated by Django 4.2.3 on 2023-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_totle_groups_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='joined_groups',
            field=models.BooleanField(default=False),
        ),
    ]
