# Generated by Django 4.2.3 on 2023-07-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_account_joined_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.account'),
        ),
    ]
